version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Ocacine10#"
      POSTGRES_DB: nepse
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s

  airflow-webserver:
    image: my-airflow-image
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:Ocacine10%23@postgres:5432/nepse"
      AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://postgres:Ocacine10%23@postgres:5432/nepse"
      AIRFLOW__CELERY__BROKER_URL: "redis://:@redis:6379/0"
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  airflow-scheduler:
    image: apache/airflow:2.9.2
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:Ocacine10%23@postgres:5432/nepse"
      AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://postgres:Ocacine10%23@postgres:5432/nepse"
      AIRFLOW__CELERY__BROKER_URL: "redis://:@redis:6379/0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    command: "airflow scheduler"  # Add this line
    depends_on:
      - postgres
      - redis


  airflow-worker:
    image: apache/airflow:2.9.2
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:Ocacine10%23@postgres:5432/nepse"
      AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://postgres:Ocacine10%23@postgres:5432/nepse"
      AIRFLOW__CELERY__BROKER_URL: "redis://:@redis:6379/0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
      - ./plugins:/opt/airflow/plugins
    command: "airflow celery worker"  # Add this line
    depends_on:
      - postgres
      - redis

volumes:
  postgres-db-volume:
